<?php 
    echo $this->headMeta();
    echo $this->headLink();
?>

<div style="padding: 8px;" class ="login">
    <table >
        <tbody>
            <tr >
                <td class="formLabel" >Tên Loại Vải</td>
                <td class="formEdit"><?=$this->element->getElement('tenloaivai'); ?></td>   
            </tr>
            <tr >
                <td class="formLabel">Thuộc Loại Sợi </td>
                <td class="formEdit" ><?=$this->element->getElement('masoi'); ?></td>
            </tr>
            <tr>
                <td class="formLabel" ></td>
                <td  class="formEdit"><?=$this->element->getElement('them'); ?></td> 
            </tr>         
        </tbody>
    </table>
</div>