<?php 
        require_once '/../header.phtml';
        echo $this->headMeta();
        echo $this->headLink();
        
        
        $hightlight ="" ;
        $choose = $this->param->getParams();
        
        if(array_key_exists('khachhang',$choose)) $hightlight = "khachhang";
        else if(array_key_exists('donhang',$choose)) $hightlight = "donhang";
        else if(array_key_exists('hopdong',$choose)) $hightlight = "hopdong";
        else if(array_key_exists('caymoc',$choose)) $hightlight = "caymoc";
        else if(array_key_exists('caymoc_detail',$choose)) $hightlight = "caymoc";
        else if(array_key_exists('taoctp',$choose)) $hightlight = "caythanhpham";
        else if(array_key_exists('lonhuom',$choose)) $hightlight = "lonhuom";
        else if(array_key_exists('khohang',$choose)) $hightlight = "khohang";
        else if(array_key_exists('caythanhpham',$choose)) $hightlight = "caythanhpham";
        else if(array_key_exists('ctp_detail',$choose)) $hightlight = "caythanhpham";
        else if(array_key_exists('khotp',$choose)) $hightlight = "khotp";
        else if(array_key_exists('donxuat',$choose)) $hightlight = "donxuat";
        else if(array_key_exists('hoadon',$choose)) $hightlight = "hoadon";
        else if(array_key_exists('loaivai',$choose)) $hightlight = "loaivai";
        else if(array_key_exists('loaisoi',$choose)) $hightlight = "loaisoi";
        else if(array_key_exists('mau',$choose)) $hightlight = "mau";
        else if(array_key_exists('nhacungcap',$choose)) $hightlight = "nhacungcap";
        else if(array_key_exists('khosoi',$choose)) $hightlight = "khosoi";
        else if(array_key_exists('khomoc',$choose)) $hightlight = "khomoc";
        else $hightlight = "khachhang";
        
        $router = Zend_Controller_Front::getInstance()->getRouter();
        $urlchitiet = $router->assemble(array('option' => 'chitiet'));
        $urlthem = $router->assemble(array('option' => 'them'));
        $urllichsu = $router->assemble(array('option' => 'lichsu'));
        
        if($hightlight == "caymoc") 
        {
            $urlthem = HOST_PROJECT."/index/xem/caymoc/true/option/them";
            $urlchitiet = HOST_PROJECT."/index/xem/caymoc/true/";
        }
        
        if($hightlight == "khomoc")
        {
            $urlchonmoc = HOST_PROJECT."/index/xem/khomoc/true/chonmoc/true/";
            $urlchitiet = HOST_PROJECT."/index/xem/khomoc/true/";
        }
?>


<div id="mainql">
    <div style="float: left">
<!--         <p class="quanly_title">Quản lý dữ liệu</p> -->
        <div style="display:block" id = "mainmenu">
            <p <?php if($hightlight=="khachhang") echo 'class ="highlight"';?> ><a  href="<?php echo HOST_PROJECT."/index/xem/khachhang/true"?>">Khách Hàng</a></p>
            <p <?php if($hightlight=="donhang") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/xem/donhang/true"?>">Đơn Hàng</a></p>
            <p <?php if($hightlight=="hopdong") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/xem/hopdong/true"?>">Hợp Đồng </a></p>
            <p <?php if($hightlight=="caymoc") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/xem/caymoc/true"?>">Cây Mộc</a></p>
            <p <?php if($hightlight=="lonhuom") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/xem/lonhuom/true"?>">Lô Nhuộm</a></p>
            <p <?php if($hightlight=="caythanhpham") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/xem/caythanhpham/true"?>">Cây Thành Phẩm</a></p>
            <p <?php if($hightlight=="khosoi") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/xem/khosoi/true"?>">Kho Sợi</a></p>
            <p <?php if($hightlight=="khomoc") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/xem/khomoc/true"?>">Kho Mộc</a></p>
            <p <?php if($hightlight=="khotp") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/xem/khotp/true"?>">Kho TP</a></p>
            <p <?php if($hightlight=="khohang") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/xem/khohang/true"?>">Kho Hàng</a></p>
            <p <?php if($hightlight=="donxuat") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/xem/donxuat/true"?>">Đơn Xuất</a></p>
            <p <?php if($hightlight=="hoadon") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/xem/hoadon/true"?>">Hóa Đơn</a></p>
            <p <?php if($hightlight=="loaivai") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/xem/loaivai/true"?>">Loại Vải</a></p>
            <p <?php if($hightlight=="loaisoi") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/xem/loaisoi/true"?>">Loại Sợi</a></p>
            <p <?php if($hightlight=="mau") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/xem/mau/true"?>">Màu</a></p>            
            <p <?php if($hightlight=="nhacungcap") echo 'class ="highlight"';?>><a  href="<?php echo HOST_PROJECT."/index/xem/nhacungcap/true"?>">Nhà Cung Cấp</a></p>
            
        </div>
        <span style="clear: both"></span>
    </div>
    
    <div>
        <?php 
        if($hightlight != "qlkho")
        {?>
        <div id= "top">
            <div class="mybutton">
                
                        <a href="<?php echo $urlchitiet ?>">Chi Tiết</a>  
                    <?php 
                    if($hightlight == "khachhang" || $hightlight == "hopdong"|| $hightlight == "caymoc"|| $hightlight == "caythanhpham"||$hightlight == "khohang" ||$hightlight == "loaivai" 
                        ||$hightlight == "loaisoi"  ||$hightlight == "mau" ||$hightlight == "lonhuom" || $hightlight == "nhacungcap")
                    {
                        ?><a href="<?php echo $urlthem ?>">Thêm</a><?php 
                    }
                    
                    if($hightlight == "caymoc")
                    {
                        ?><a href="<?php echo $urllichsu ?>">Lịch Sử</a><?php
                    }
                    
                    if($hightlight == "khomoc")
                    {
                        
                        ?><a href="<?php echo $urlchonmoc ?>">Chọn Mộc</a><?php
                    }
                ?>
            </div>            
           
        </div>
        
        <div id="bodycontent">

            <?php 
                $option = $this->param->getParam("option");

                if($option==null || $option =="chitiet")
                    require_once 'chitiet.php';
                else if( $option == "them")
                    require_once 'them.php';
                else if($option == "lichsu")
                    require_once APPLICATION_PATH.'/layouts/xem/caymoc/caymoc_lichsu.php';
            ?>

        </div>
        <?php 
        }
        else 
        {
            echo "<div class= 'qlkho'>";
            require_once 'chitiet.php';
            echo "</div>";
        }
        
        ?>
    </div>  
    <span style="clear: both"></span>
</div>
