<?php 
    echo $this->headMeta();
    echo $this->headLink();
?>

<div style="padding: 8px;" class ="login">
    <table >
        <tbody>
            <tr >
                <td class="formLabel">Số Mét Vải</td>
                <td class="formEdit" ><?=$this->element->getElement('sometvai'); ?></td>
                <td  style="padding-left:20px;"><?=$this->element->getElement('them'); ?></td> 
            </tr>        
        </tbody>
    </table>
</div>