<?php 
    echo $this->headMeta();
    echo $this->headLink();
?>

<div style="padding: 8px;" class ="login">
    <table >
        <tbody>
            <tr >
                <td class="formLabel" >Loại Vải</td>
                <td class="formEdit"><?=$this->element->getElement('mavai'); ?></td>   
            </tr>
            <tr >
                <td class="formLabel">Màu Vải</td>
                <td class="formEdit" ><?=$this->element->getElement('mamau'); ?></td>
            </tr>
            <tr >
                <td class="formLabel" >Số Mét Vải</td>
                <td class="formEdit"><?=$this->element->getElement('sometvai'); ?></td>   
            </tr>
            <tr >
                <td class="formLabel" >Ngày Đặt Hàng</td>
                <td class="formEdit"><?=$this->element->getElement('ngaydathang'); ?></td>   
            </tr>
             
            <tr>
               <td class="formLabel" ></td>
              <td  class="formEdit"><?=$this->element->getElement('them'); ?></td> 
            </tr>         
        </tbody>
    </table>
</div>