<?php 
    echo $this->headMeta();
    echo $this->headLink();
    echo $this->headScript();
?>
<div id="header" >
    <div id="container">
        <ul >
            <li  class="menu-item"><a href="<?php echo HOST_PROJECT."/index/main"?>" >Khách Hàng</a></li>
            <li class="menu-item"><a href="<?php echo HOST_PROJECT."/index/xem/"?>">Quản Trị</a></li>
            <li class="menu-item"><a href="<?php echo HOST_PROJECT."/index/main/congty/true"?>">Công Ty</a></li>
            <li class="menu-item"><a href="<?php echo HOST_PROJECT."/index/nhaplieu/muasoi/true"?>">Mua Sợi</a></li>
            <li class="menu-item"><a href="<?php echo HOST_PROJECT."/index/taichinh"?>">Tài Chính</a></li>
            <li class="menu-item"><a href="<?php echo HOST_PROJECT."/index/tim"?>">Tìm kiếm</a></li>
            <li class="menu-item"><a href="<?php echo HOST_PROJECT."/index/thongke"?>">Thống kê</a></li>
            <li class="menu-item"><a href="<?php echo HOST_PROJECT."/index/main/dutru/true"?>">Dự Trù</a></li>
            <li class="menu-item"><a href="<?php echo HOST_PROJECT."/index/export"?>">Xuất File</a></li>
            <li class="menu-item"><a href="<?php echo HOST_PROJECT."/index/logout"?>">Logout</a></li>
        </ul>
    </div>
</div>
