<?php
?>
<div style="float: left">
<p class="quanly_title">Quản lý dữ liệu</p>
<div style="display:block" id = "mainmenu">
<p  ><a  href="<?php echo HOST_PROJECT."/index/xem/khachhang/true"?>">Khách Hàng</a></p>
<p ><a  href="<?php echo HOST_PROJECT."/index/xem/donhang/true"?>">Đơn Hàng</a></p>
<p ><a  href="<?php echo HOST_PROJECT."/index/xem/hopdong/true"?>">Hợp Đồng </a></p>
<p ><a  href="<?php echo HOST_PROJECT."/index/xem/caymoc/true"?>">Cây Vải</a></p>
<p ><a  href="<?php echo HOST_PROJECT."/index/xem/lonhuom/true"?>">Lô Nhuộm</a></p>
<p ><a  href="<?php echo HOST_PROJECT."/index/xem/donxuat/true"?>">Đơn Xuất</a></p>
<p ><a  href="<?php echo HOST_PROJECT."/index/xem/hoadon/true"?>">Thanh Toán</a></p>
<p ><a  href="<?php echo HOST_PROJECT."/index/xem/loaivai/true"?>">Loại Vải</a></p>
<p ><a  href="<?php echo HOST_PROJECT."/index/xem/loaisoi/true"?>">Loại Sợi</a></p>
<p ><a  href="<?php echo HOST_PROJECT."/index/xem/mau/true"?>">Màu</a></p>
<p ><a  href="<?php echo HOST_PROJECT."/index/xem/khohang/true"?>">Kho Sợi</a></p>
<p ><a  href="<?php echo HOST_PROJECT."/index/xem/khohang/true"?>">Kho Mộc</a></p>
<p ><a  href="<?php echo HOST_PROJECT."/index/xem/khohang/true"?>">Kho Vải</a></p>
<p ><a  href="<?php echo HOST_PROJECT."/index/xem/qlkho/true"?>">Quản Lý Kho</a></p>
<p ><a  href="<?php echo HOST_PROJECT."/index/xem/nhacungcap/true"?>">Nhà Cung Cấp</a></p>

</div>
<span style="clear: both"></span>
</div>