<?php 
    echo $this->headMeta();
    echo $this->headLink();
?>

<div style="padding: 8px;" class ="login">
    <table >
        <tbody>
            <tr >
                <td class="formLabel" >Tên kho hàng</td>
                <td class="formEdit"><?=$this->element->getElement('chonkhohang'); ?></td>   
            </tr>
            <tr>
              <td class="formLabel" ></td>
              <td  class="formEdit"><?=$this->element->getElement('them'); ?></td> 
            </tr>         
        </tbody>
    </table>
</div>