<?php 
    echo $this->headMeta();
    echo $this->headLink();
?>

<div style="padding: 8px;margin-left:40px;" class ="login">
    <table >
        <tbody>
            <tr >
                <td class="formLabel" >Nhà Cung Cấp</td>
                <td class="formEdit"><?=$this->element->getElement('manhacungcap'); ?></td>
                <td style="padding-left: 25px;"><?=$this->element->getElement('them'); ?></td>
            </tr>

                        
        </tbody>
    </table>
</div>